config/routes.rb
SurveyBuilder::Application.routes.draw do

  resources :users
  resources :surveys
  resources :questions

  match '/users', :to => 'users#show'
  match '/new_survey', :to => 'surveys#new'
  match '/new_question', :to => 'questions#new'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match 'surveys/take/:id', :to => 'surveys#take'
  match 'surveys/results/:id', :to => 'surveys#results'
  match 'surveys/total/:id', :to => 'surveys#total'
  
  root :to => 'pages#home'

end

app/models/question.rb
# == Schema Information
# Schema version: 20110428053629
#
# Table name: questions
#
#  id         :integer         not null, primary key
#  content    :string(255)
#  survey_id  :integer
#  created_at :datetime
#  updated_at :datetime
#

class Question < ActiveRecord::Base
  attr_accessible :content
  
  belongs_to :survey
  has_many :results, :dependent => :destroy
  
  validates :content, :presence => true
  validates :survey_id, :presence => true
  
end

app/models/result.rb
# == Schema Information
# Schema version: 20110429001548
#
# Table name: results
#
#  id          :integer         not null, primary key
#  score       :integer
#  question_id :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Result < ActiveRecord::Base
  attr_accessible :score, :question_id
  
  belongs_to :question
  
  validates :score, :presence => true
  validates :question_id, :presence => true
end

app/models/survey.rb
# == Schema Information
# Schema version: 20110428024225
#
# Table name: surveys
#
#  id          :integer         not null, primary key
#  name        :string(255)
#  description :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class Survey < ActiveRecord::Base
  attr_accessible :name, :description
  
  has_many :questions, :dependent => :destroy
end

app/models/user.rb
# == Schema Information
# Schema version: 20110427223206
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  type_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
  attr_accessible :name, :type_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
    unless params[:users1] == nil
      @id = params[:users1][:id]
      @user = User.find(@id)
      @type = @user.type_id
      session[:type] = @type.to_s
      session[:name] = @user.name
      redirect_to(surveys_path)
    end
  end

  def about
    @title = "about"
  end
  
  def help
    @title = "Help"
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
  def new
    @question = Question.new
    @title = "New Question"
  end
  
  def create
    @question = Question.new(params[:question])
    @survey = session[:survey]
    @question.survey_id = @survey.id
    if @question.save
      flash[:success] = "Question created."
      redirect_to @survey
    else
      redirect_to @survey
    end
  end
  
  def edit
    @title = "Edit Question"
    @question = Question.find(params[:id])
  end
  
  def update
    @question = Question.find(params[:id])
    @survey = session[:survey]
    if @question.update_attributes(params[:question])
      flash[:success] = "Question updated."
      redirect_to @survey
    else
      @title = "Edit Question"
      render 'edit'
    end
  end
  
  def destroy
    Question.find(params[:id]).destroy
    flash[:success] = "Question deleted."
    redirect_to session[:survey]
  end

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_filter :check_user, :only => []
  
  def index
    @title = "All Surveys"
    @surveys = Survey.all.paginate(:page => params[:page], :per_page => 6)
    @counter = 0
  end
  
  def new
    @survey = Survey.new
    @title = "New Survey"
  end
  
  def create
    @survey = Survey.new(params[:survey])
    if @survey.save
      flash[:success] = "Survey created."
      redirect_to surveys_path
    else
      redirect_to surveys_path
    end
  end
  
  def show
    @survey = Survey.find(params[:id])
    session[:survey] = @survey
    #@microposts = @user.microposts.all.paginate(:page => params[:page], :per_page => 10)
    @questions = @survey.questions.all
    @title = @survey.name
    @counter = 0
  end
  
  def destroy
    Survey.find(params[:id]).destroy
    flash[:success] = "Survey destroyed."
    redirect_to surveys_path
  end
  
  def take
    @survey = Survey.find(params[:id])
    @questions = @survey.questions.all
    @title = @survey.name
    @counter = 0
  end
  
  def results
    @survey = Survey.find(params[:id])
    @questions = @survey.questions.all
    @new_results = {}
    @title = @survey.name + " Results"
    @counter = 0
    for q in @questions
      if params["score" + q.id.to_s] == nil #no answer
        flash[:error] = "Missing Answers"
        redirect_to "/surveys/take/" + params[:id]
        return
      end
    end
    for q in @questions
      @score = params["score" + q.id.to_s][:score_v]
      @result = Result.create(:score => @score, :question_id => q.id.to_s)
      @new_results[q.id.to_s] = @score
    end
  end
  
  def total
    @survey = Survey.find(params[:id])
    @questions = @survey.questions.all
    @title = @survey.name + " Results"
    @counter = 0
  end
  
  private
    
    def check_user
      #redirect_to(root_path) unless session[:type] == '0'
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @title = @user.name
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Return a title on a per-page basis.
  def title
    base_title = "Survey Builder"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
  
  def logo
    image_tag("survey_blue.jpg",:height => "200",
      :alt => "Survey Builder", :class => "round")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
	  
      <li> &copy <%= link_to " 2011 Nirari Barm", about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
		<%= link_to logo, root_path %>
        <nav class="round">
          <ul>
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Surveys", surveys_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Help", help_path %></li>
          </ul>
        </nav>
      </header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->  
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
  <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
  <%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= title%> </title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <%= render 'layouts/stylesheets'%>
</head>
<body>
 <div class="container">
      <%= render 'layouts/header'%>
      <section class="round">
		<% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
	  <%= render 'layouts/footer' %>
	  <!--<%= debug(params) if Rails.env.development? %>-->
    </div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
    <p>
      Project created for CS 441 at <a href="http://uic.edu/">UIC</a> by Nirari Barm
    </p>
 <p>
    CSS styles from Sample App tutorial on <%= link_to "http://ruby.railstutorial.org" %>
</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>
  READ ME!
</p>

app/views/pages/home.html.erb
<h1 align="center">Welcome to Survey Builder 1.0 Beta</h1>
<br>
<p>
<%= form_tag(root_path, :method => "post") do %>
    <h2 align="center" >
      Choose a user:
    </h2>
	<p align="center">
	<%=  select("users1", "id", 
       User.all.collect {|p| [ p.name, p.id] }) %>
	<br>
	<br>
	<%= submit_tag("Start!", :class => "signup_button round")%>
	</p>
<% end %>
</p>

app/views/questions/_question.html.erb
  <br>
  (<%= @counter = @counter + 1 %>) <%= question.content%>
	<% if session[:type] == '0' || session[:type] == '1' %>
	  <br> --options: <%= link_to "edit", edit_question_path(question.id)%> |
   <%= link_to "delete", question, :method => :delete, :confirm => "You sure?",
                                :title => "Delete Question" %>
  <% end %>

  <br>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= form_for(@question) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/questions/new.html.erb
<h1>Create Question</h1>

<%= form_for(@question) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit "Create" %>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> 
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %> 
        from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/surveys/_survey.html.erb
<li>
  [<%= @counter = @counter + 1 %>] <%= survey.name%>: <%= survey.description%>
	  <br> --options: 
	<% if session[:type] == '0' || session[:type] == '1' || session[:type] == '2'%> 
	<%= link_to "take", "/surveys/take/" + survey.id.to_s %> 
   <% end %>
	<% if session[:type] == '0' || session[:type] == '1'%> 
	|
   <% end %>
	<% if session[:type] == '0' || session[:type] == '1' || session[:type] == '3'%> 
	<%= link_to "results", "/surveys/total/" + survey.id.to_s%>
   <% end %>
	<% if session[:type] == '0' || session[:type] == '1'%> | <%= link_to "edit", survey%>
   <% end %>
	<% if session[:type] == '0' %>
  | <%= link_to "delete", survey, :method => :delete, :confirm => "You sure?",
                                :title => "Delete #{survey.name}" %>
  <% end %>

  <br>
  <br>
</li>

app/views/surveys/index.html.erb
<table class="profile" summary="Survey information">
  <tr>
    <td class="main">
		<h1 align="center">Surveys</h1>

		<%= will_paginate %>
		
		<ul class="users">
		  <%= render @surveys %>
		</ul>
		
		<%= will_paginate %>
		<p align="center">
		<% if session[:type] == '0' %>
		  <%= link_to "Add a new Survey", new_survey_path%>
		<% end %>
		</p>
    </td>
    <td class="sidebar round">
	  <br><strong><%= session[:name]%> </strong>
      <br><%= link_to "Change User", root_path %>
    </td>
  </tr>
</table>

app/views/surveys/new.html.erb
<h1>Create Survey</h1>

<%= form_for(@survey) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit "Create" %>
  </div>
<% end %>

app/views/surveys/results.html.erb
<table class="profile" summary="Survey information">
  <tr>
    <td class="main">
      <h1 align="center">
        <%= "Your Results"%>
      </h1>
	    Description: <%= @survey.description %>
		<br><br>
				<% unless @questions.empty? %>
		        <table class="questions" summary="survey questions">
		          		<% for q in @questions do%>
							(<%= @counter = @counter + 1 %>) <%= q.content%> <br>
							<%= @new_results[q.id.to_s]%>
							<br>
							<br>
						<% end %>
		        </table>
		      <% end %>
		</p>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @survey.name %><br />
      <strong>URL</strong> <%= link_to survey_path(@survey), @survey %><br />
      <strong>Questions</strong> <%= @survey.questions.count %>
	  <br><br><strong><%= session[:name]%> </strong>
      <br><%= link_to "Change User", root_path %>
      <br><br><%= link_to "Back to Surveys", surveys_path %>
    </td>
  </tr>
</table>

app/views/surveys/show.html.erb
<table class="profile" summary="Survey information">
  <tr>
    <td class="main">
      <h1 align="center">
        Editing <%= @survey.name %>
      </h1>
	    Description: <%= @survey.description %>
		<br> <br> Questions:
				<% unless @survey.questions.empty? %>
		        <table class="questions" summary="survey questions">
		          <%= render @questions %>
		        </table>
		      <% end %>
		<p align="center">
		<% if session[:type] == '0' || session[:type] == '1' %>
		  <%= link_to "Add a new Question", new_question_path%>
		<% end %>
		</p>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @survey.name %><br />
      <strong>URL</strong> <%= link_to survey_path(@survey), @survey %><br />
      <strong>Questions</strong> <%= @survey.questions.count %>
	  <br><br><strong><%= session[:name]%> </strong>
      <br><%= link_to "Change User", root_path %>
      <br><br><%= link_to "Back to Surveys", surveys_path %>
    </td>
  </tr>
</table>

app/views/surveys/take.html.erb
<table class="profile" summary="Survey information">
  <tr>
    <td class="main">
      <h1 align="center">
        <%= @survey.name %>
      </h1>
	    Description: <%= @survey.description %>
		<br><br>Answer each question by clicking a response between:
		<br>(1) Low / Least Likely and (5) High / Most Likely. <br><br>
				<% unless @questions.empty? %>
		        <table class="questions" summary="survey questions">
					<%= form_tag("/surveys/results/" + @survey.id.to_s) do %>
		          		<% for q in @questions do%>
							(<%= @counter = @counter + 1 %>) <%= q.content%> <br>
							<%= radio_button "score" + q.id.to_s, "score_v", 1, %>1
							<%= radio_button "score" + q.id.to_s, "score_v", 2, %>2
							<%= radio_button "score" + q.id.to_s, "score_v", 3, %>3
							<%= radio_button "score" + q.id.to_s, "score_v", 4, %>4
							<%= radio_button "score" + q.id.to_s, "score_v", 5, %>5
							<br>
							<br>
						<% end %>
						<%= submit_tag("Submit!")%>
			      	<% end %>
		        </table>
		      <% end %>
		</p>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @survey.name %><br />
      <strong>URL</strong> <%= link_to survey_path(@survey), @survey %><br />
      <strong>Questions</strong> <%= @survey.questions.count %>
	  <br><br><strong><%= session[:name]%> </strong>
      <br><%= link_to "Change User", root_path %>
      <br><br><%= link_to "Back to Surveys", surveys_path %>
    </td>
  </tr>
</table>

app/views/surveys/total.html.erb
<table class="profile" summary="Survey information">
  <tr>
    <td class="main">
      <h1 align="center">
        <%= "Total Results"%>
      </h1>
	    Description: <%= @survey.description %>
		<br><br>
				<% unless @questions.empty? %>
		        <table class="questions" summary="survey questions">
		          		<% for q in @questions do%>
							(<%= @counter = @counter + 1 %>) <%= q.content%> <br>
							<% @results = q.results.all %>
							<% @count = 0 %>
							Answers: 
							<% for r in @results do%>
								<%= r.score %> 
								<% @count = @count + r.score%>
							<% end %> 
                            <br>SUM = <%= @count %>
							, AVG = <%= q.results.count != 0?(@count.to_f / q.results.count.to_f).round(1):0%>
							<br>
							<br>
						<% end %>
		        </table>
		      <% end %>
		</p>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @survey.name %><br />
      <strong>URL</strong> <%= link_to survey_path(@survey), @survey %><br />
      <strong>Questions</strong> <%= @survey.questions.count %>
	  <br><br><strong><%= session[:name]%> </strong>
      <br><%= link_to "Change User", root_path %>
      <br><br><%= link_to "Back to Surveys", surveys_path %>
    </td>
  </tr>
</table>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1>
        <%= @user.name %>
      </h1>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>URL</strong>  <%= link_to user_path(@user), @user %>
    </td>
  </tr>
</table>